palette =  0=#090618
palette =  1=#E46876
palette =  2=#6A9589
palette =  3=#c0a36e
palette =  4=#7e9cd8
palette =  5=#957fb8
palette =  6=#7AA89F
palette =  7=#c8c093
palette =  8=#727169
palette =  9=#e82424
palette = 10=#76946A
palette = 11=#e6c384
palette = 12=#7fb4ca
palette = 13=#938aa9
palette = 14=#A3D4D5
palette = 15=#dcd7ba
palette = 16=#1F1F28
palette = 17=#43242B
palette = 18=#2B3328
palette = 19=#49443C
palette = 20=#223249
palette = 21=#D27E99
palette = 22=#2D4F67
palette = 23=#54546D

background = 121212
foreground = F8F8F8
cursor-color = FFFFFF
selection-background = 2d4f67
selection-foreground = dcd7ba

