palette =  0=#241B2F
palette =  1=#f53fa1
palette =  2=#72F1B8
palette =  3=#FFCC00
palette =  4=#633aff
palette =  5=#FF7EDB
palette =  6=#61E2FF
palette =  7=#F8F8F8
palette =  8=#495495
palette =  9=#bf8afa
palette = 10=#39795c
palette = 11=#ffd633
palette = 12=#9275ff
palette = 13=#ff98e2
palette = 14=#81e8ff
palette = 15=#ffffff
background = 121212
foreground = F8F8F8
cursor-color = 63cdcf
cursor-text = C0FF98
selection-background = 44495d
selection-foreground = c6d0f5
