palette =  0=#0b0e16
palette =  1=#b84856
palette =  2=#389060
palette =  3=#c08e52
palette =  4=#4f5fb4
palette =  5=#8a68c8
palette =  6=#4e93a8
palette =  7=#c6d0e0
palette =  8=#7a85a6
palette =  9=#e05a6a
palette = 10=#48b878
palette = 11=#e0a868
palette = 12=#6e86e0
palette = 13=#b492ec
palette = 14=#86c8dc
palette = 15=#e8f0f8
palette = 16=#05060a
palette = 17=#0b0e16
palette = 18=#121726
palette = 19=#1c2233
palette = 20=#2b344d
palette = 21=#303888
palette = 22=#8a6a3a
palette = 23=#a8bcf0

background = 05060a
foreground = e8f0f8
cursor-color = e0a868
cursor-text = 05060a
selection-background = 2b344d
selection-foreground = e8f8f8
