[UNKWN000000003581]
dpi_x = 1800
dpi_y = 1800
poll_rate = 500
backlight_active = True
backlight_brightness = 70
backlight_effect = static
backlight_colors = 0 255 255 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 2
logo_active = True
logo_brightness = 75
logo_effect = none
logo_colors = 0 255 0 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 75
scroll_effect = spectrum
scroll_colors = 0 255 0 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

