[Appearance]
color_scheme_path=~/.themes/Netrunner/qt6ct/Netrunner.conf
custom_palette=true
style=Windows

[Fonts]
fixed="Berkeley Mono,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Berkeley Mono,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
stylesheets=/home/m/.themes/Netrunner/qt6ct/Netrunner.qss

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\xff\xff\xff\x10\0\0\f{\0\0\x4t\0\0\a\x80\xff\xff\xff\x10\0\0\f{\0\0\x4t\0\0\0\0\0\0\0\0\n\0\0\0\a\x80\xff\xff\xff\x10\0\0\f{\0\0\x4t)
