local M = {}

--[[
 Every group is a full spec, no links to groups defined in the same table,
 so that a single override cannot cascade into unrelated parts of the UI.
]]

function M.get(c, opts)
  local bg = opts.transparent and "NONE" or c.void
  local bg_side = opts.transparent and "NONE" or c.panel
  local bg_status = opts.transparent and "NONE" or c.panel_hi

  return {
    -- [ Editor ]-------------------------------------------------------- --
    Normal = { fg = c.text, bg = bg },
    NormalNC = { fg = c.text, bg = bg },
    NormalFloat = { fg = c.text, bg = c.panel },
    FloatBorder = { fg = c.line_hi, bg = c.panel },
    FloatTitle = { fg = c.amber, bg = c.panel, bold = true },
    Cursor = { fg = c.void, bg = c.amber },
    lCursor = { fg = c.void, bg = c.amber },
    CursorIM = { fg = c.void, bg = c.amber },
    TermCursor = { fg = c.void, bg = c.amber },
    TermCursorNC = { fg = c.void, bg = c.dim },
    CursorLine = { bg = c.panel_hi },
    CursorColumn = { bg = c.panel_hi },
    ColorColumn = { bg = c.panel_hi },
    Conceal = { fg = c.dim },
    NonText = { fg = c.line_hi },
    EndOfBuffer = { fg = c.line, bg = bg },
    SpecialKey = { fg = c.line_hi },
    Whitespace = { fg = c.line },
    Directory = { fg = c.blue },
    Title = { fg = c.blue_lt, bold = true },
    Folded = { fg = c.muted, bg = c.panel },
    FoldColumn = { fg = c.dim, bg = bg },
    SignColumn = { fg = c.dim, bg = bg },
    LineNr = { fg = c.dim, bg = bg },
    LineNrAbove = { fg = c.dim, bg = bg },
    LineNrBelow = { fg = c.dim, bg = bg },
    CursorLineNr = { fg = c.amber, bg = bg, bold = true },
    CursorLineFold = { fg = c.dim, bg = bg },
    CursorLineSign = { fg = c.dim, bg = bg },
    MatchParen = { fg = c.amber_lt, bg = c.line_hi, bold = true },
    Visual = { bg = c.line_hi },
    VisualNOS = { bg = c.line_hi },
    Search = { fg = c.amber_lt, bg = c.bg_search },
    IncSearch = { fg = c.void, bg = c.amber_lt, bold = true },
    CurSearch = { fg = c.void, bg = c.amber, bold = true },
    Substitute = { fg = c.void, bg = c.bad, bold = true },
    QuickFixLine = { bg = c.line, bold = true },
    WinSeparator = { fg = c.line_hi, bg = bg },
    VertSplit = { fg = c.line_hi, bg = bg },
    WinBar = { fg = c.muted, bg = bg },
    WinBarNC = { fg = c.dim, bg = bg },
    StatusLine = { fg = c.text_dk, bg = bg_status },
    StatusLineNC = { fg = c.dim, bg = bg_side },
    TabLine = { fg = c.muted, bg = c.panel },
    TabLineFill = { bg = bg },
    TabLineSel = { fg = c.blue_hi, bg = c.line_hi, bold = true },
    Pmenu = { fg = c.text_dk, bg = c.panel },
    PmenuSel = { fg = c.blue_hi, bg = c.line_hi, bold = true },
    PmenuKind = { fg = c.blue, bg = c.panel },
    PmenuKindSel = { fg = c.blue_hi, bg = c.line_hi },
    PmenuExtra = { fg = c.muted, bg = c.panel },
    PmenuExtraSel = { fg = c.text_dk, bg = c.line_hi },
    PmenuMatch = { fg = c.amber, bg = c.panel, bold = true },
    PmenuMatchSel = { fg = c.amber_lt, bg = c.line_hi, bold = true },
    PmenuSbar = { bg = c.line },
    PmenuThumb = { bg = c.line_hi },
    WildMenu = { fg = c.blue_hi, bg = c.line_hi, bold = true },
    ErrorMsg = { fg = c.bad, bold = true },
    WarningMsg = { fg = c.warn },
    ModeMsg = { fg = c.blue_lt, bold = true },
    MoreMsg = { fg = c.blue },
    MsgArea = { fg = c.text_dk },
    MsgSeparator = { fg = c.line_hi, bg = bg },
    Question = { fg = c.ok },
    SpellBad = { sp = c.bad, undercurl = true },
    SpellCap = { sp = c.warn, undercurl = true },
    SpellLocal = { sp = c.cyan_lt, undercurl = true },
    SpellRare = { sp = c.violet_lt, undercurl = true },
    DiffAdd = { bg = c.bg_add },
    DiffChange = { bg = c.bg_change },
    DiffDelete = { fg = c.red_dk, bg = c.bg_delete },
    DiffText = { bg = c.bg_text },
    Added = { fg = c.ok },
    Changed = { fg = c.blue },
    Removed = { fg = c.bad },
    Bold = { bold = true },
    Italic = { italic = true },
    Underlined = { fg = c.blue, underline = true },

    -- [ Syntax ]-------------------------------------------------------- --
    Comment = { fg = c.muted },
    Constant = { fg = c.violet_lt },
    String = { fg = c.ok },
    Character = { fg = c.ok },
    Number = { fg = c.violet_lt },
    Float = { fg = c.violet_lt },
    Boolean = { fg = c.violet_lt },
    Identifier = { fg = c.text },
    Function = { fg = c.blue_lt },
    Statement = { fg = c.amber },
    Conditional = { fg = c.amber },
    Repeat = { fg = c.amber },
    Label = { fg = c.amber_lt },
    Operator = { fg = c.blue },
    Keyword = { fg = c.amber },
    Exception = { fg = c.bad },
    PreProc = { fg = c.violet_lt },
    Include = { fg = c.amber },
    Define = { fg = c.violet_lt },
    Macro = { fg = c.violet_lt },
    PreCondit = { fg = c.violet_lt },
    Type = { fg = c.cyan_lt },
    StorageClass = { fg = c.amber },
    Structure = { fg = c.cyan_lt },
    Typedef = { fg = c.cyan_lt },
    Special = { fg = c.amber_lt },
    SpecialChar = { fg = c.amber_lt },
    SpecialComment = { fg = c.blue },
    Tag = { fg = c.blue },
    Delimiter = { fg = c.muted },
    Debug = { fg = c.bad },
    Ignore = { fg = c.dim },
    Error = { fg = c.bad, bold = true },
    Todo = { fg = c.void, bg = c.amber, bold = true },

    -- [ Treesitter ]---------------------------------------------------- --
    ["@variable"] = { fg = c.text },
    ["@variable.builtin"] = { fg = c.bad },
    ["@variable.parameter"] = { fg = c.text_dk },
    ["@variable.member"] = { fg = c.blue },
    ["@constant"] = { fg = c.violet_lt },
    ["@constant.builtin"] = { fg = c.violet_lt },
    ["@constant.macro"] = { fg = c.violet_lt },
    ["@module"] = { fg = c.cyan_lt },
    ["@module.builtin"] = { fg = c.cyan_lt },
    ["@label"] = { fg = c.amber_lt },
    ["@string"] = { fg = c.ok },
    ["@string.documentation"] = { fg = c.green_dk },
    ["@string.regexp"] = { fg = c.cyan_lt },
    ["@string.escape"] = { fg = c.amber_lt },
    ["@string.special"] = { fg = c.amber_lt },
    ["@string.special.symbol"] = { fg = c.violet_lt },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@string.special.path"] = { fg = c.cyan_lt },
    ["@character"] = { fg = c.ok },
    ["@character.special"] = { fg = c.amber_lt },
    ["@boolean"] = { fg = c.violet_lt },
    ["@number"] = { fg = c.violet_lt },
    ["@number.float"] = { fg = c.violet_lt },
    ["@type"] = { fg = c.cyan_lt },
    ["@type.builtin"] = { fg = c.cyan },
    ["@type.definition"] = { fg = c.cyan_lt },
    ["@type.qualifier"] = { fg = c.amber },
    ["@attribute"] = { fg = c.violet_lt },
    ["@attribute.builtin"] = { fg = c.violet_lt },
    ["@property"] = { fg = c.blue },
    ["@function"] = { fg = c.blue_lt },
    ["@function.builtin"] = { fg = c.blue_lt },
    ["@function.call"] = { fg = c.blue_lt },
    ["@function.macro"] = { fg = c.violet_lt },
    ["@function.method"] = { fg = c.blue_lt },
    ["@function.method.call"] = { fg = c.blue_lt },
    ["@constructor"] = { fg = c.cyan_lt },
    ["@operator"] = { fg = c.blue },
    ["@keyword"] = { fg = c.amber },
    ["@keyword.coroutine"] = { fg = c.amber },
    ["@keyword.function"] = { fg = c.amber },
    ["@keyword.operator"] = { fg = c.amber },
    ["@keyword.import"] = { fg = c.amber },
    ["@keyword.type"] = { fg = c.amber },
    ["@keyword.modifier"] = { fg = c.amber },
    ["@keyword.repeat"] = { fg = c.amber },
    ["@keyword.return"] = { fg = c.amber_lt },
    ["@keyword.debug"] = { fg = c.bad },
    ["@keyword.exception"] = { fg = c.bad },
    ["@keyword.conditional"] = { fg = c.amber },
    ["@keyword.conditional.ternary"] = { fg = c.blue },
    ["@keyword.directive"] = { fg = c.violet_lt },
    ["@keyword.directive.define"] = { fg = c.violet_lt },
    ["@punctuation.delimiter"] = { fg = c.muted },
    ["@punctuation.bracket"] = { fg = c.text_dk },
    ["@punctuation.special"] = { fg = c.amber },
    ["@comment"] = { fg = c.muted },
    ["@comment.documentation"] = { fg = c.muted },
    ["@comment.error"] = { fg = c.void, bg = c.bad, bold = true },
    ["@comment.warning"] = { fg = c.void, bg = c.warn, bold = true },
    ["@comment.todo"] = { fg = c.void, bg = c.amber, bold = true },
    ["@comment.note"] = { fg = c.void, bg = c.cyan_lt, bold = true },
    ["@markup.heading"] = { fg = c.blue_hi, bold = true },
    ["@markup.heading.1"] = { fg = c.amber_lt, bold = true },
    ["@markup.heading.2"] = { fg = c.amber, bold = true },
    ["@markup.heading.3"] = { fg = c.blue_lt, bold = true },
    ["@markup.heading.4"] = { fg = c.blue, bold = true },
    ["@markup.heading.5"] = { fg = c.cyan_lt, bold = true },
    ["@markup.heading.6"] = { fg = c.muted, bold = true },
    ["@markup.strong"] = { fg = c.text, bold = true },
    ["@markup.italic"] = { fg = c.text, italic = true },
    ["@markup.strikethrough"] = { fg = c.muted, strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.quote"] = { fg = c.muted },
    ["@markup.math"] = { fg = c.violet_lt },
    ["@markup.link"] = { fg = c.blue_lt },
    ["@markup.link.label"] = { fg = c.blue_lt },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.raw"] = { fg = c.cyan_lt },
    ["@markup.raw.block"] = { fg = c.cyan_lt },
    ["@markup.list"] = { fg = c.amber },
    ["@markup.list.checked"] = { fg = c.ok },
    ["@markup.list.unchecked"] = { fg = c.muted },
    ["@diff.plus"] = { fg = c.ok },
    ["@diff.minus"] = { fg = c.bad },
    ["@diff.delta"] = { fg = c.blue },
    ["@tag"] = { fg = c.blue_lt },
    ["@tag.builtin"] = { fg = c.blue_lt },
    ["@tag.attribute"] = { fg = c.cyan_lt },
    ["@tag.delimiter"] = { fg = c.muted },
    ["@conceal"] = { fg = c.dim },
    ["@error"] = { fg = c.bad, bold = true },
    ["@none"] = {},

    -- [ LSP ]----------------------------------------------------------- --
    ["@lsp.type.namespace"] = { fg = c.cyan_lt },
    ["@lsp.type.type"] = { fg = c.cyan_lt },
    ["@lsp.type.class"] = { fg = c.cyan_lt },
    ["@lsp.type.enum"] = { fg = c.cyan_lt },
    ["@lsp.type.interface"] = { fg = c.cyan_lt },
    ["@lsp.type.struct"] = { fg = c.cyan_lt },
    ["@lsp.type.typeParameter"] = { fg = c.cyan },
    ["@lsp.type.parameter"] = { fg = c.text_dk },
    ["@lsp.type.variable"] = { fg = c.text },
    ["@lsp.type.property"] = { fg = c.blue },
    ["@lsp.type.enumMember"] = { fg = c.violet_lt },
    ["@lsp.type.function"] = { fg = c.blue_lt },
    ["@lsp.type.method"] = { fg = c.blue_lt },
    ["@lsp.type.macro"] = { fg = c.violet_lt },
    ["@lsp.type.decorator"] = { fg = c.violet_lt },
    ["@lsp.type.keyword"] = { fg = c.amber },
    ["@lsp.type.operator"] = { fg = c.blue },
    ["@lsp.type.string"] = { fg = c.ok },
    ["@lsp.type.number"] = { fg = c.violet_lt },
    ["@lsp.type.comment"] = { fg = c.muted },
    ["@lsp.mod.deprecated"] = { fg = c.muted, strikethrough = true },
    DiagnosticError = { fg = c.bad },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan_lt },
    DiagnosticOk = { fg = c.ok },
    DiagnosticSignError = { fg = c.bad, bg = bg },
    DiagnosticSignWarn = { fg = c.warn, bg = bg },
    DiagnosticSignInfo = { fg = c.blue, bg = bg },
    DiagnosticSignHint = { fg = c.cyan_lt, bg = bg },
    DiagnosticSignOk = { fg = c.ok, bg = bg },
    DiagnosticVirtualTextError = { fg = c.bad, bg = c.bg_error },
    DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.bg_warn },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.bg_info },
    DiagnosticVirtualTextHint = { fg = c.cyan_lt, bg = c.bg_hint },
    DiagnosticVirtualTextOk = { fg = c.ok, bg = c.bg_add },
    DiagnosticUnderlineError = { sp = c.bad, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.warn, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan_lt, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.ok, undercurl = true },
    DiagnosticFloatingError = { fg = c.bad, bg = c.panel },
    DiagnosticFloatingWarn = { fg = c.warn, bg = c.panel },
    DiagnosticFloatingInfo = { fg = c.blue, bg = c.panel },
    DiagnosticFloatingHint = { fg = c.cyan_lt, bg = c.panel },
    DiagnosticFloatingOk = { fg = c.ok, bg = c.panel },
    DiagnosticUnnecessary = { fg = c.dim },
    DiagnosticDeprecated = { fg = c.muted, strikethrough = true },
    LspReferenceText = { bg = c.line },
    LspReferenceRead = { bg = c.line },
    LspReferenceWrite = { bg = c.line_hi },
    LspSignatureActiveParameter = { fg = c.amber, bold = true },
    LspInlayHint = { fg = c.dim, bg = c.panel },
    LspCodeLens = { fg = c.dim },
    LspInfoBorder = { fg = c.line_hi, bg = c.panel },
    healthError = { fg = c.bad },
    healthWarning = { fg = c.warn },
    healthSuccess = { fg = c.ok },

    -- [ Telescope ]----------------------------------------------------- --
    TelescopeNormal = { fg = c.text_dk, bg = c.panel },
    TelescopeBorder = { fg = c.line_hi, bg = c.panel },
    TelescopeTitle = { fg = c.muted },
    TelescopePromptNormal = { fg = c.text, bg = c.panel_hi },
    TelescopePromptBorder = { fg = c.blue_dk, bg = c.panel_hi },
    TelescopePromptTitle = { fg = c.void, bg = c.amber, bold = true },
    TelescopePromptPrefix = { fg = c.amber, bg = c.panel_hi },
    TelescopePromptCounter = { fg = c.dim, bg = c.panel_hi },
    TelescopeResultsNormal = { fg = c.text_dk, bg = c.panel },
    TelescopeResultsBorder = { fg = c.line_hi, bg = c.panel },
    TelescopeResultsTitle = { fg = c.void, bg = c.blue, bold = true },
    TelescopeResultsDiffAdd = { fg = c.ok },
    TelescopeResultsDiffChange = { fg = c.blue },
    TelescopeResultsDiffDelete = { fg = c.bad },
    TelescopePreviewNormal = { fg = c.text_dk, bg = c.panel },
    TelescopePreviewBorder = { fg = c.line_hi, bg = c.panel },
    TelescopePreviewTitle = { fg = c.void, bg = c.ok, bold = true },
    TelescopePreviewLine = { bg = c.line },
    TelescopeSelection = { fg = c.blue_hi, bg = c.line_hi },
    TelescopeSelectionCaret = { fg = c.amber, bg = c.line_hi },
    TelescopeMultiSelection = { fg = c.amber_lt, bg = c.line },
    TelescopeMultiIcon = { fg = c.amber },
    TelescopeMatching = { fg = c.amber, bold = true },

    -- [ Neo-tree ]------------------------------------------------------ --
    NeoTreeNormal = { fg = c.text_dk, bg = bg_side },
    NeoTreeNormalNC = { fg = c.text_dk, bg = bg_side },
    NeoTreeEndOfBuffer = { fg = c.line, bg = bg_side },
    NeoTreeWinSeparator = { fg = c.line_hi, bg = bg_side },
    NeoTreeCursorLine = { bg = c.line },
    NeoTreeRootName = { fg = c.amber, bold = true },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeFileName = { fg = c.text_dk },
    NeoTreeFileNameOpened = { fg = c.blue_hi },
    NeoTreeFileIcon = { fg = c.muted },
    NeoTreeIndentMarker = { fg = c.line_hi },
    NeoTreeExpander = { fg = c.dim },
    NeoTreeDimText = { fg = c.dim },
    NeoTreeDotfile = { fg = c.dim },
    NeoTreeHiddenByName = { fg = c.dim },
    NeoTreeMessage = { fg = c.dim },
    NeoTreeModified = { fg = c.warn },
    NeoTreeSymbolicLinkTarget = { fg = c.cyan_lt },
    NeoTreeFilterTerm = { fg = c.amber, bold = true },
    NeoTreeTitleBar = { fg = c.void, bg = c.blue, bold = true },
    NeoTreeFloatBorder = { fg = c.line_hi, bg = c.panel },
    NeoTreeFloatTitle = { fg = c.amber, bg = c.panel, bold = true },
    NeoTreeTabActive = { fg = c.blue_hi, bg = c.panel_hi, bold = true },
    NeoTreeTabInactive = { fg = c.dim, bg = c.panel },
    NeoTreeTabSeparatorActive = { fg = c.panel_hi, bg = c.panel_hi },
    NeoTreeTabSeparatorInactive = { fg = c.panel, bg = c.panel },
    NeoTreeGitAdded = { fg = c.ok },
    NeoTreeGitModified = { fg = c.blue },
    NeoTreeGitDeleted = { fg = c.bad },
    NeoTreeGitRenamed = { fg = c.violet_lt },
    NeoTreeGitUntracked = { fg = c.violet_lt },
    NeoTreeGitIgnored = { fg = c.dim },
    NeoTreeGitConflict = { fg = c.warn, bold = true },
    NeoTreeGitStaged = { fg = c.ok },
    NeoTreeGitUnstaged = { fg = c.warn },

    -- [ Completion ]---------------------------------------------------- --
    CmpItemAbbr = { fg = c.text_dk },
    CmpItemAbbrDeprecated = { fg = c.dim, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.amber, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.amber_lt, bold = true },
    CmpItemMenu = { fg = c.muted },
    CmpItemKindDefault = { fg = c.muted },
    CmpItemKindText = { fg = c.muted },
    CmpItemKindFunction = { fg = c.blue_lt },
    CmpItemKindMethod = { fg = c.blue_lt },
    CmpItemKindConstructor = { fg = c.blue_lt },
    CmpItemKindVariable = { fg = c.text_dk },
    CmpItemKindValue = { fg = c.text_dk },
    CmpItemKindField = { fg = c.blue },
    CmpItemKindProperty = { fg = c.blue },
    CmpItemKindClass = { fg = c.cyan_lt },
    CmpItemKindInterface = { fg = c.cyan_lt },
    CmpItemKindStruct = { fg = c.cyan_lt },
    CmpItemKindEnum = { fg = c.cyan_lt },
    CmpItemKindTypeParameter = { fg = c.cyan_lt },
    CmpItemKindModule = { fg = c.cyan },
    CmpItemKindUnit = { fg = c.cyan },
    CmpItemKindReference = { fg = c.cyan },
    CmpItemKindEvent = { fg = c.cyan },
    CmpItemKindKeyword = { fg = c.amber },
    CmpItemKindOperator = { fg = c.amber },
    CmpItemKindSnippet = { fg = c.violet_lt },
    CmpItemKindConstant = { fg = c.violet_lt },
    CmpItemKindEnumMember = { fg = c.violet_lt },
    CmpItemKindFile = { fg = c.blue },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindColor = { fg = c.amber_lt },
    CmpDocumentation = { fg = c.text_dk, bg = c.panel },
    CmpDocumentationBorder = { fg = c.line_hi, bg = c.panel },

    -- [ Which-key ]----------------------------------------------------- --
    WhichKey = { fg = c.amber },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.text_dk },
    WhichKeySeparator = { fg = c.dim },
    WhichKeyValue = { fg = c.muted },
    WhichKeyNormal = { fg = c.text, bg = c.panel },
    WhichKeyFloat = { bg = c.panel },
    WhichKeyBorder = { fg = c.line_hi, bg = c.panel },
    WhichKeyTitle = { fg = c.amber, bg = c.panel, bold = true },
    WhichKeyIconAzure = { fg = c.blue },
    WhichKeyIconBlue = { fg = c.blue },
    WhichKeyIconCyan = { fg = c.cyan_lt },
    WhichKeyIconGreen = { fg = c.ok },
    WhichKeyIconGrey = { fg = c.muted },
    WhichKeyIconOrange = { fg = c.amber },
    WhichKeyIconPurple = { fg = c.violet_lt },
    WhichKeyIconRed = { fg = c.bad },
    WhichKeyIconYellow = { fg = c.amber_lt },
    MiniIconsAzure = { fg = c.blue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.cyan_lt },
    MiniIconsGreen = { fg = c.ok },
    MiniIconsGrey = { fg = c.muted },
    MiniIconsOrange = { fg = c.amber },
    MiniIconsPurple = { fg = c.violet_lt },
    MiniIconsRed = { fg = c.bad },
    MiniIconsYellow = { fg = c.amber_lt },

    -- [ Noice ]--------------------------------------------------------- --
    NoiceCmdline = { fg = c.text_dk, bg = bg },
    NoiceCmdlineIcon = { fg = c.amber },
    NoiceCmdlineIconSearch = { fg = c.amber_lt },
    NoiceCmdlinePrompt = { fg = c.amber },
    NoiceCmdlinePopup = { fg = c.text, bg = c.panel },
    NoiceCmdlinePopupBorder = { fg = c.blue_dk, bg = c.panel },
    NoiceCmdlinePopupTitle = { fg = c.amber, bg = c.panel, bold = true },
    NoiceConfirm = { fg = c.text, bg = c.panel },
    NoiceConfirmBorder = { fg = c.line_hi, bg = c.panel },
    NoiceMini = { fg = c.muted, bg = c.panel },
    NoiceVirtualText = { fg = c.amber },
    NoicePopupmenu = { fg = c.text_dk, bg = c.panel },
    NoicePopupmenuSelected = { fg = c.blue_hi, bg = c.line_hi, bold = true },
    NoicePopupmenuBorder = { fg = c.line_hi, bg = c.panel },
    NoicePopupmenuMatch = { fg = c.amber, bold = true },
    NoiceScrollbar = { bg = c.panel },
    NoiceScrollbarThumb = { bg = c.line_hi },
    NoiceFormatProgressDone = { fg = c.void, bg = c.ok },
    NoiceFormatProgressTodo = { fg = c.text_dk, bg = c.line },
    NoiceLspProgressTitle = { fg = c.text_dk },
    NoiceLspProgressClient = { fg = c.blue },
    NoiceLspProgressSpinner = { fg = c.amber },

    -- [ Notify ]-------------------------------------------------------- --
    NotifyBackground = { bg = c.panel },
    NotifyERRORBorder = { fg = c.bad, bg = c.panel },
    NotifyERRORIcon = { fg = c.bad },
    NotifyERRORTitle = { fg = c.bad, bold = true },
    NotifyERRORBody = { fg = c.text_dk, bg = c.panel },
    NotifyWARNBorder = { fg = c.warn, bg = c.panel },
    NotifyWARNIcon = { fg = c.warn },
    NotifyWARNTitle = { fg = c.warn, bold = true },
    NotifyWARNBody = { fg = c.text_dk, bg = c.panel },
    NotifyINFOBorder = { fg = c.blue, bg = c.panel },
    NotifyINFOIcon = { fg = c.blue },
    NotifyINFOTitle = { fg = c.blue, bold = true },
    NotifyINFOBody = { fg = c.text_dk, bg = c.panel },
    NotifyDEBUGBorder = { fg = c.dim, bg = c.panel },
    NotifyDEBUGIcon = { fg = c.muted },
    NotifyDEBUGTitle = { fg = c.muted, bold = true },
    NotifyDEBUGBody = { fg = c.text_dk, bg = c.panel },
    NotifyTRACEBorder = { fg = c.violet, bg = c.panel },
    NotifyTRACEIcon = { fg = c.violet_lt },
    NotifyTRACETitle = { fg = c.violet_lt, bold = true },
    NotifyTRACEBody = { fg = c.text_dk, bg = c.panel },

    -- [ Trouble ]------------------------------------------------------- --
    TroubleNormal = { fg = c.text_dk, bg = bg_side },
    TroubleNormalNC = { fg = c.text_dk, bg = bg_side },
    TroubleText = { fg = c.text_dk },
    TroubleCount = { fg = c.amber, bg = c.line },
    TroubleSource = { fg = c.muted },
    TroublePos = { fg = c.dim },
    TroubleIndent = { fg = c.line_hi },
    TroubleIndentFoldClosed = { fg = c.amber },
    TroubleIndentFoldOpen = { fg = c.dim },
    TroubleDirectory = { fg = c.muted },
    TroubleFilename = { fg = c.blue },
    TroubleBasename = { fg = c.blue_lt },
    TroubleIconDirectory = { fg = c.blue },
    TroubleIconFilename = { fg = c.blue_lt },
    TroublePreview = { bg = c.line },

    -- [ Flash, marks, grug-far ]---------------------------------------- --
    FlashLabel = { fg = c.void, bg = c.amber, bold = true },
    FlashMatch = { fg = c.blue_hi, bg = c.blue_dk },
    FlashCurrent = { fg = c.void, bg = c.amber_lt, bold = true },
    FlashBackdrop = { fg = c.dim },
    MarkSignHL = { fg = c.amber, bg = bg },
    MarkSignNumHL = { fg = c.dim, bg = bg },
    MarkVirtTextHL = { fg = c.muted },
    GrugFarHelpHeader = { fg = c.blue },
    GrugFarHelpHeaderKey = { fg = c.amber },
    GrugFarInputLabel = { fg = c.blue },
    GrugFarInputPlaceholder = { fg = c.dim },
    GrugFarResultsHeader = { fg = c.blue_lt },
    GrugFarResultsStats = { fg = c.muted },
    GrugFarResultsPath = { fg = c.cyan_lt },
    GrugFarResultsLineNo = { fg = c.dim },
    GrugFarResultsLineColumn = { fg = c.dim },
    GrugFarResultsMatch = { fg = c.amber_lt, bg = c.bg_search },
    GrugFarResultsMatchAdded = { fg = c.ok, bg = c.bg_add },
    GrugFarResultsMatchRemoved = {
      fg = c.bad,
      bg = c.bg_delete,
      strikethrough = true,
    },
    GrugFarResultsChangeIndicator = { fg = c.amber },
    GrugFarResultsCmdHeader = { fg = c.violet_lt },
    GrugFarResultsActionMessage = { fg = c.ok },
  }
end

return M
