"$schema" = 'https://starship.rs/config-schema.json'

add_newline=false
#scan_timeout = 10
format = '$character$directory'
right_format = '$terraform$git_state$git_status$git_branch$git_commit${custom.rad}$battery'

[character]
success_symbol = '[▲](green)'
error_symbol = '[▲](red)'
vicmd_symbol = '[△](cyan)'

[directory]
style = 'cyan'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
rebase = '[rebasing](bold magenta)'
merge = '[merging](bold yellow)'
revert = '[reverting](bold blue)'
cherry_pick = '[picking](bold red)'
bisect = '[bisecting](bold red)'
am = '[applying](bold green)'
am_or_rebase = '[applying/rebasing](bold yellow)'

[git_status]
format = '([$all_status $ahead_behind]($style) )'
style = '8'
up_to_date = ''
untracked = '.'
conflicted = '#'
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
stashed = '^'
modified = '*'
staged = '+'
renamed = '»'
deleted = 'x'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ''
style = '8'
truncation_length = 16
truncation_symbol = ''
ignore_branches = []

[git_commit]
format = ' [$hash$tag]($style)'
style = '8'
only_detached = false
commit_hash_length = 6
tag_symbol = ''

[terraform] 
format = '[$symbol$workspace]($style) '
style = '105'
symbol = ' '

[battery]
full_symbol = '\[F\]'
charging_symbol = '\[+\]'
discharging_symbol = '\[-\]'
empty_symbol = '\[ \]'
unknown_symbol = '\[?\]'
format = ' [$percentage](black) [$symbol]($style)'
[[battery.display]]
threshold = 25
style = 'yellow'

[custom.rad]
command = 'rad inspect --rid'
require_repo = true
when = true
format = ' [$symbol($output )]($style)'
style = '#8585FF'
