theme[main_bg]="#05060a"
theme[main_fg]="#e8f0f8"
theme[title]="#a8bcf0"
theme[hi_fg]="#e0a868"
theme[selected_bg]="#121726"
theme[selected_fg]="#e0a868"
theme[inactive_fg]="#4d5772"
theme[graph_text]="#7a85a6"
theme[meter_bg]="#1c2233"
theme[proc_misc]="#a8bcf0"

theme[cpu_box]="#2b344d"
theme[mem_box]="#2b344d"
theme[net_box]="#2b344d"
theme[proc_box]="#2b344d"
theme[div_line]="#1c2233"

theme[temp_start]="#4f5fb4"
theme[temp_mid]="#c08e52"
theme[temp_end]="#ffd79a"

theme[cpu_start]="#6e86e0"
theme[cpu_mid]="#e0a868"
theme[cpu_end]="#ffd79a"

theme[free_start]="#303888"
theme[free_mid]="#4f5fb4"
theme[free_end]="#6e86e0"

theme[cached_start]="#8a6a3a"
theme[cached_mid]="#c08e52"
theme[cached_end]="#e0a868"

theme[available_start]="#4f5fb4"
theme[available_mid]="#6e86e0"
theme[available_end]="#a8bcf0"

theme[used_start]="#6e86e0"
theme[used_mid]="#e0a868"
theme[used_end]="#ffd79a"

theme[download_start]="#303888"
theme[download_mid]="#6e86e0"
theme[download_end]="#a8bcf0"

theme[upload_start]="#8a6a3a"
theme[upload_mid]="#e0a868"
theme[upload_end]="#ffd79a"

theme[process_start]="#4f5fb4"
theme[process_mid]="#e0a868"
theme[process_end]="#ffd79a"

theme[proc_pause_bg]="#8a6a3a"
theme[proc_follow_bg]="#303888"
theme[proc_banner_bg]="#121726"
theme[proc_banner_fg]="#a8bcf0"
theme[followed_bg]="#303888"
theme[followed_fg]="#e8f8f8"
