wtf:
  colors:
    border:
      focusable: cyan
      focused: white
      normal: cyan
    checked: "gray"
    highlight:
      fore: "white"
      # back: "green"
    text: "white"
    title: "white"
  grid:
    columns: [20, 20, 20, 20, 20, 20, 20, 20]
    rows: [12, 10, 10, 10, 10, 10, 10, 10, 10, 10]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: white 
          odd: grey
      enabled: true
      locations:
        Berlin: "Europe/Berlin"
        London: "Europe/London"
        New York: "America/New York"
        Panama: "America/Panama"
        Los Angeles: "America/Los Angeles"
        Honolulu: "Pacific/Honolulu"
        Tokyo: "Asia/Tokyo"
        Melbourne: "Australia/Melbourne"
        Seoul: "Asia/Seoul"
        Bangkok: "Asia/Bangkok"
      position:
        left: 0
        top: 0
        width: 2
        height: 1
      refreshInterval: 1m
      sort: "chronological"

    ipinfo:
      colors:
        name: "#75d5ff"
        value: white
      enabled: true
      position:
        left: 0
        top: 1
        width: 2
        height: 1
      refreshInterval: 1h

    github:
      enabled: true
      enableStatus: true
      showMyPullRequests: true 
      showOpenReviewRequests: true 
      showStats: true 
      username: "mrusme"
      repositories:
        - "mrusme/zeit"
      position:
        left: 2
        top: 0
        width: 4
        height: 2
      refreshInterval: 5m

    kubernetes:
      enabled: true
      kubeconfig: "/home/mrus/.kube/cbsh-dev-kubernetes.yaml"
      namespaces:
      - cbsh-dev
      - cert-manager
      - internal
      - public 
      - system
      objects:
      - deployments
      - nodes
      - pods
      position:
        left: 6
        top: 0
        width: 4
        height: 4
      refreshInterval: 5m
      title: "cloudbuild dev"

    feedreader:
      enabled: true
      feeds:
      - https://soylentnews.org/index.atom
      feedLimit: 8
      position:
        left: 0
        top: 2
        width: 6
        height: 1
      refreshInterval: 2h

    hackernews:
      enabled: true
      numberOfStories: 8
      position:
        left: 0
        top: 3
        width: 6
        height: 1
      storyType: top
      refreshInterval: 2h

