return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter").install({
        "arduino",
        "bash",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        -- "dockerfile",
        "editorconfig",
        "eex",
        -- "elixir",
        -- "erlang",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gowork",
        "gpg",
        "graphql",
        "haskell",
        "hcl",
        "helm",
        "html",
        "http",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "kconfig",
        "latex",
        "ledger",
        "llvm",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "nginx",
        "ninja",
        "nix",
        "objdump",
        "passwd",
        "po",
        "printf",
        "rbs",
        "readline",
        "regex",
        "requirements",
        "ruby",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "strace",
        "svelte",
        "todotxt",
        "toml",
        "tsv",
        "typescript",
        "udev",
        "vim",
        "xml",
        "yaml",
        "zig",
      })

      vim.api.nvim_create_autocmd("FileType", {
        group = vim.api.nvim_create_augroup("treesitter_highlight", {}),
        callback = function(args)
          pcall(vim.treesitter.start, args.buf)
        end,
      })
    end,
  },
}
