return {
  {
    "nvim-treesitter/nvim-treesitter", 
    build = ":TSUpdate",
    config = function()
      local configs = require("nvim-treesitter.configs")
      configs.setup({
        ensure_installed = { 
          "arduino",
          "bash",
          "c", 
          "cmake",
          "comment",
          "cpp",
          "css",
          "csv",
          "diff",
          -- "dockerfile",
          "editorconfig",
          "eex",
          -- "elixir",
          -- "erlang",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go", 
          "gomod",
          "gosum",
          "gotmpl",
          "gowork",
          "gpg",
          "graphql",
          "haskell",
          "hcl",
          "helm",
          "html",
          "http",
          "javascript",
          "jq",
          "jsdoc",
          "json",
          "json5",
          "jsonc",
          "kconfig",
          "latex",
          "ledger",
          "llvm",
          "lua", 
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "meson",
          "muttrc",
          "nginx",
          "ninja",
          "nix",
          "objdump",
          "org",
          "passwd",
          "po",
          "printf",
          "rbs",
          "readline",
          "regex",
          "requirements",
          "robots",
          "ruby",
          "rust",
          "scss",
          "sql",
          "ssh_config",
          "strace",
          "svelte",
          "tmux",
          "todotxt",
          "toml",
          "tsv",
          "typescript", 
          "udev",
          "vim",
          "xml",
          "yaml",
          "zathurarc",
          "zig"
        },

        sync_install = false,
        ignore_install = {},

        highlight = {
          enable = true,
          disable = {},
          additional_vim_regex_highlighting = false,
        },
      })
    end
  }
}
