[general]
live_config_reload = true
working_directory = "None"

[bell]
animation = "Linear"
color = "#463465"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
dim_foreground    = "#aeafb0"
bright_foreground = "#f28779"
background        = "#121212"
foreground        = "#F8F8F8"

[colors.cursor]
text = "#C0FF98"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#cdcecf"
cursor = "#63cdcf"

[colors.search.matches]
foreground = "#cdcecf"
background = "#3c5372"

[colors.search.focused_match]
foreground = "#cdcecf"
background = "#81b29a"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#29394f"

[colors.hints.start]
foreground = "#cdcecf"
background = "#f4a261"

[colors.hints.end]
foreground = "#cdcecf"
background = "#29394f"

[colors.selection]
text = "#F8F8F8"
background = "#463465"

[colors.normal]
black = "#241B2F"
red = "#f53fa1"
green = "#72F1B8"
yellow = "#FFCC00"
blue = "#633aff"
magenta = "#FF7EDB"
cyan = "#61E2FF"
white = "#F8F8F8"

[colors.bright]
black = "#495495"
red = "#bf8afa"
green = "#39795c"
yellow = "#ffd633"
blue = "#9275ff"
magenta = "#ff98e2"
cyan = "#81e8ff"
white = "#ffffff"

[colors.dim]
black = "#18121f"
red = "#cd0b73"
green = "#16e287"
yellow = "#b38f00"
blue = "#633aff"
magenta = "#ff0cbb"
cyan = "#00c9f6"
white = "#aeaeae"

[[colors.indexed_colors]]
index = 16
color = "#f4a261"

[[colors.indexed_colors]]
index = 17
color = "#d67ad2"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
#ref_test = false
render_timer = false

[font]
size = 11
builtin_box_drawing = false

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Regular"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.bold_italic]
family = "Berkeley Mono"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
chars = "\u001B[1;3H"
key = "Home"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;3F"
key = "End"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5;3~"
key = "PageUp"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mode = "Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6;3~"
key = "PageDown"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Super"

[[keyboard.bindings]]
chars = """

"""
key = "NumpadEnter"

[[keyboard.bindings]]
chars = "\u0001c"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001="
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001-"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001n"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001p"
key = "Tab"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0001,"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[D"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[C"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[A"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[B"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2A"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2B"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2D"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2C"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001\u001B[1;2B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00010"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "None"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.90
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 28

[window.padding]
x = 8
y = 8

[[hints.enabled]]
command = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[terminal]
