theme = "netrunner"

[editor]
color-modes = true
mouse = false
middle-click-paste = false
scrolloff = 10
scroll-lines = 1
line-number = "absolute"
cursorline = true
continue-comments = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
path-completion = true
auto-format = true
rulers = [80]
end-of-line-diagnostics = "hint"
default-yank-register="+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "˽"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "disable"

[editor.soft-wrap]
wrap-indicator = ""

[keys.normal]
"C-c" = "normal_mode"
C-s = ":w"
C-q = ":q"
C-r = ":reload"
C-a = "select_all"
V = ["extend_line_below", "select_mode"]
D = "@t<ret>d"
G = "@ge"
"C-/" = "toggle_comments"
"C-\"" = "@f\"lmi\""
"C-'" = "@f'lmi'"
"C-(" = "@f(lmi("
"C-[" = "@f[lmi["
"C-{" = "@f{lmi{"
"," = {
  "," = "keep_primary_selection",
  f = "@X:reflow<ret>"
}
C-v = "save_selection"

[keys.insert]
"C-c" = "normal_mode"
C-s = [":w", "normal_mode"]
C-q = "normal_mode"
C-a = ["normal_mode", "select_all"]
"C-/" = "toggle_comments"
